services:
  nebula:
    build: .
    restart: unless-stopped
    volumes:
    - ./config:/config:ro
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "4252:4252/udp"
version: '2.4'
